### PR TITLE
Weekly minor patch release `2.0.7` [rebase & merge]

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

Fixes #\<issue_number>

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

cc @borda @carmocca @justusschock @awaelchli

### CODE REVIEW

**Comment by Borda** [comment]
This is true weakness of our App testing, when production server is won also several our unit-tests are failing...
```
=========================== short test summary info ============================
FAILED tests_app/cli/test_cmd_install.py::test_valid_org_app_name - assert "app: 'fakeuser/ALKKLJAUHREKJ21234KLAKJDLF' is not available on ⚡ Lightning AI ⚡" in ''
 +  where '' = <Result JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>.output
FAILED tests_app/cli/test_cmd_install.py::test_valid_org_component_name - assert "component: 'fakeuser/ALKKLJAUHREKJ21234KLAKJDLF' is not available on ⚡ Lightning AI ⚡" in ''
 +  where '' = <Result JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>.output
FAILED tests_app/cli/test_cmd_install.py::test_prompt_actions - AssertionError: assert 'Installation aborted!' in ''
 +  where '' = <Result JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>.output
FAILED tests_app/cli/test_cmd_install.py::test_version_arg_component - assert "component: 'Version NOT-EXIST for lightning/lit-slack-messenger' is not" in 'Expecting value: line 1 column 1 (char 0)'
 +  where 'Expecting value: line 1 column 1 (char 0)' = str(JSONDecodeError('Expecting value: line 1 column 1 (char 0)'))
 +    where JSONDecodeError('Expecting value: line 1 column 1 (char 0)') = <Result JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>.exception
FAILED tests_app/cli/test_cmd_install.py::test_version_arg_app - assert "app: 'Version NOT-EXIST for lightning/invideo' is not" in 'Expecting value: line 1 column 1 (char 0)'
 +  where 'Expecting value: line 1 column 1 (char 0)' = str(JSONDecodeError('Expecting value: line 1 column 1 (char 0)'))
 +    where JSONDecodeError('Expecting value: line 1 column 1 (char 0)') = <Result JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>.exception
FAILED tests_app/cli/test_cmd_install.py::test_proper_url_parsing - requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
FAILED tests_app/cli/test_cmd_install.py::test_app_and_component_gallery_app - requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
FAILED tests_app/cli/test_cmd_install.py::test_app_and_component_gallery_component - requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
= 8 failed, 668 passed, 57 skipped, 3 xfailed, 1 xpassed, 80 warnings in 459.57s (0:07:39) =
```
these shall be mocked or moved to integrations

**Comment by Borda** [comment]
@awaelchli I have seen this test fail a few times, have you seen it also on `master`? and do you think it flaky?
```
FAILED strategies/test_ddp_integration.py::test_ddp_save_load[cpu] - torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/runner/work/lightning/lightning/src/lightning/fabric/strategies/launchers/multiprocessing.py", line 126, in _wrapping_function
    results = function(*args, **kwargs)
  File "/home/runner/work/lightning/lightning/src/lightning/fabric/fabric.py", line 781, in _run_with_setup
    return run_function(*args, **kwargs)
  File "/home/runner/work/lightning/lightning/tests/tests_fabric/strategies/test_ddp_integration.py", line 56, in _run_ddp_save_load
    fabric.load(tmp_path / "saved_after_setup.ckpt", {"model": model})
  File "/home/runner/work/lightning/lightning/src/lightning/fabric/fabric.py", line 652, in load
    return self._strategy.load_checkpoint(path=path, state=state)
  File "/home/runner/work/lightning/lightning/src/lightning/fabric/strategies/strategy.py", line 284, in load_checkpoint
    checkpoint = self.checkpoint_io.load_checkpoint(path)
  File "/home/runner/work/lightning/lightning/src/lightning/fabric/plugins/io/torch_io.py", line 89, in load_checkpoint
    raise FileNotFoundError(f"Checkpoint at {path} not found. Aborting training.")
FileNotFoundError: Checkpoint at /tmp/pytest-of-runner/pytest-0/test_ddp_save_load_cpu_0/saved_after_setup.ckpt not found. Aborting training.
= 1 failed, 546 passed, 197 skipped, 22 warnings, 1 rerun in 126.99s (0:02:06) =
```

**Comment by awaelchli** [comment]
I found these commits were missing here:
https://github.com/Lightning-AI/lightning/pull/18137
https://github.com/Lightning-AI/lightning/pull/18129
https://github.com/Lightning-AI/lightning/pull/18226 (not sure if needed)
https://github.com/Lightning-AI/lightning/pull/18280
https://github.com/Lightning-AI/lightning/pull/18267

There are also several with no milestone that look like they need to be included, for example:
https://github.com/Lightning-AI/lightning/pull/18186
https://github.com/Lightning-AI/lightning/pull/18155
https://github.com/Lightning-AI/lightning/pull/18151

**Comment by Borda** [comment]
> There are also several with no milestone that look like they need to be included, for example:
> #18186
> #18155
> #18151

the `data` are not in the stable branch and I would also rather skip the launch command for 2.1 as a user can try it with `2.1.0.rc0` later today...

**Review by awaelchli — APPROVED** [review]

**Review by justusschock — APPROVED** [review]

**Pull request merged**
