### PR TITLE
rename flow _exit

### PR DESCRIPTION
**Pull request by justusschock**
## What does this PR do?

Renames `LightningFlow._exit` to `LightningFlow.stop` to expose it to users and be more consistent with Works.
Discussed offline with @lantiga 

### Does your PR introduce any breaking changes? If yes, please list them.
None, since this was protected before.

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @borda @justusschock @awaelchli

### CODE REVIEW

**Review by awaelchli — APPROVED** [review]
Not sure what the state of this work is, but we would need to ensure that calling stop() terminates all resources (also locally). See also the on_exit() hooks on Work.

**Review by Borda — APPROVED** [review]

**Comment by awaelchli** [comment]
The difference now is that the method is public. I'm bringing the awareness to what would have to be done to complete the feature's intentional use.

**Comment by Borda** [comment]
@justusschock the test is failing specifically for this use case (package/os) so there is not randomness... could we revisit what is happening there...

**Comment by justusschock** [comment]
@Borda I just reran the tests and it passed, so there is some randomness :D

**Comment by lantiga** [comment]
This may break existing user apps or apps in the gallery, can we add a deprecated `_exit` just to be sure?

**Pull request merged**
