### PR TITLE
Call `wandb.finish` in the `WandbLogger.finalize`

### PR DESCRIPTION
**Pull request by kunaltyagi**
## What does this PR do?

This ensures the logger is ready to create a new run once finalize has been called

Fixes #\<issue_number>

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
  - No
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you verify new and **existing tests pass** locally with your changes?

No to all these
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

----
:books: Documentation preview :books:: https://pytorch-lightning--18659.org.readthedocs.build/en/18659/

### CODE REVIEW

**Comment by awaelchli** [comment]
Hey @kunaltyagi 
This might be unexpected for some users and is not consistent with how the other loggers work. For example, if you did training and then testing,

```
trainer.fit(model)
trainer.test(model)
```
then this PR will now make it so that you end up with two runs in your WandB dashboard, whereas previously both the training and testing metrics were logged to the same run. Wouldn't it be better if we let the user decide to finish the run or not? I think it's really use-case dependent.

**Comment by kunaltyagi** [comment]
I wasn't aware that the finalize is called automatically. I've been using it manually so far

**Comment by kunaltyagi** [comment]
Can you point me to the code where this would be called at the end of `fit`? It'd help me understand the flow better

**Comment by awaelchli** [comment]
Finalize gets called here on teardown:
https://github.com/Lightning-AI/lightning/blob/363da4aa8539efe8d81ac5b3937b7fe4c8efe4fa/src/lightning/pytorch/trainer/call.py#L128-L129

The teardown happens here in the trainer after every trainer call (fit, test etc.):
https://github.com/Lightning-AI/lightning/blob/363da4aa8539efe8d81ac5b3937b7fe4c8efe4fa/src/lightning/pytorch/trainer/trainer.py#L1004

Yes you can call `wandb.finish()` manually yourself if you want, to force the run to be ended and a new one to be created the next time the logger is called.

**Comment by kunaltyagi** [comment]
Based on this, I'll close the PR

**Comment by awaelchli** [comment]
We could mention it more prominently in our wandb docs if you think that's better.

**Pull request closed without merging**
