### PR TITLE
Include app templates to the lightning and app packages

### PR DESCRIPTION
**Pull request by manskx**
## What does this PR do?

Adding app templates to the lightning package.

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @borda @tchaton @rohitgr7

### CODE REVIEW

**Review by rohitgr7 — APPROVED** [review]

**Comment by adam-lightning** [comment]
Was the issue regarding missing templates in release package finally created? Just wondering if we can link this PR to it.

**Comment by Borda** [comment]
> Was the issue regarding missing templates in release package finally created? Just wondering if we can link this PR to it.

this issue is related to the last release `0.5.2`

**Review by Borda — APPROVED** [review]

**Comment by williamFalcon** [comment]
@manskx 
what templates are these?

**Comment by manskx** [comment]
> @manskx what templates are these?

@williamFalcon  these are the templates used to create a lightning app from the CLI, e.g. `init pl-app ./train_script.py` or `lightning init react-ui`

**Comment by williamFalcon** [comment]
these shouldn’t live in this repo… this needs to live in the pl-app repo

**Comment by manskx** [comment]
> these shouldn’t live in this repo… this template is specific to the lightning app repo, it should live there. We don’t need to bloat everyone’s install with unnecessary files.
> 
> cc @lantiga

@awaelchli as far as I remember, these templates were added for a reason ?

**Comment by awaelchli** [comment]
Yes, the templates should be included of course. Otherwise we can't use them from the CLI. This is just the code that we added to the app repo.

**Comment by luca-medeiros** [comment]
The related issue https://github.com/Lightning-AI/lightning/issues/13745

**Review by awaelchli — APPROVED** [review]

**Comment by manskx** [comment]
> @williamFalcon I agree with keeping templates independent, however in order to do so properly we need to take care of cross-version compatibility. @manskx will kick off a GH issue shortly so we can figure out the details.
> 
> For the time being I'd strongly suggest to still expose the templates at the package level following this PR, so we fix the experience for users.

Created the issue here: https://github.com/Lightning-AI/lightning/issues/13757

I am going to enable auto-merge this to fix the package now.

**Pull request merged**
