### PR TITLE
move changelogs to standalone folders

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

pesonaly I would rather see the changelog outside the package/python tree

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

### CODE REVIEW

**Review by justusschock — CHANGES_REQUESTED** [review]
I am very much against this change.
If you have a local installation of lightning, the default folders do exist and are on python path if you installed in editable mode.

Things like https://github.com/Lightning-AI/lightning/blob/master/src/lightning/app/components/multi_node/trainer.py#L51 where we actually need to import from both packages when present to make sure it also works with standalone PL (or Fabric), require me to delete the standalone folders to not get ImportErrors just because of the folder existence.

If we move the changelog there, I cannot do this anymore while still editing the changelog locally.

I would appreciate a  lot if we could actually get rid of standalone folders

**Comment by awaelchli** [comment]
I'm also for getting rid of the standalone folders entirely. We can already see that contributors get confused, and make source code modifications in the [wrong files](https://github.com/Lightning-AI/lightning/pull/16866/commits/38283a59fb890f19e133dc725b8a21c97387bdcf) (lightning_fabric instead of lightning/fabric).

**Comment by awaelchli** [comment]
Since the standalone packages get generated anyway, one could just move/generate these files and if you want, also remove the changelogs from the subfolder. Just an idea.

**Comment by Borda** [comment]
> We can already see that contributors get confused, and make source code modifications in the [wrong files](https://github.com/Lightning-AI/lightning/pull/16866/commits/38283a59fb890f19e133dc725b8a21c97387bdcf) (lightning_fabric instead of lightning/fabric).

This won't change with del dir as you can see, it was one line cnage, so user created PR from state before refactoring

> Things like [`master`/src/lightning/app/components/multi_node/trainer.py#L51](https://github.com/Lightning-AI/lightning/blob/master/src/lightning/app/components/multi_node/trainer.py?rgh-link-date=2023-02-24T14%3A45%3A27Z#L51) where we actually need to import from both packages when present to make sure it also works with standalone PL (or Fabric), require me to delete the standalone folders to not get ImportErrors just because of the folder existence.

Not sure how delete folder helps here as this line need to stay uncless we abendent stanlone packages (not only folder for it)

**Pull request closed without merging**
