### PR TITLE
Update for Muse

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

some minor fixes...

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @tchaton @rohitgr7 @borda

### CODE REVIEW

**Review by awaelchli — APPROVED** [review]
@Borda I think it should say in the description that this is cherry picking
https://github.com/Lightning-AI/lightning/commit/2721a2f06b8044826ba23be93695e62994850b7a

This helps the reviewer.

**Comment by Borda** [comment]
> I think it should say in the description that this is cherry picking [2721a2f](https://github.com/Lightning-AI/lightning/commit/2721a2f06b8044826ba23be93695e62994850b7a)
> 
> This helps the reviewer.

You are right, it is just not sure what all needs to be picked, so switching back to draft...

**Comment by Borda** [comment]
also we need to get #14972

**Comment by otaj** [comment]
Although it's for pytorch portion, it is needed since doctests for app are importing pytorch portion as well

**Review by tchaton — APPROVED** [review]
LGTM !

**Review by otaj — APPROVED** [review]

**Review by manskx — APPROVED** [review]

**Pull request merged**
