### PR TITLE
Releasing/1.8.4

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

TBD

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @borda

### CODE REVIEW

**Comment by Borda** [comment]
trying to resolve the hanging benchmarks in #15879

**Comment by Borda** [comment]
resolving the failing TOU tests (in fact the tests even won't start) in #15876

**Comment by Borda** [comment]
also would be good to have #15798

**Comment by Borda** [comment]
adding automation in #15871 and #15887

**Comment by Borda** [comment]
seem the failing PL-cpu test are green but the CI/check ends-up red :otter:

**Comment by Borda** [comment]
@tchaton see like all e2e tests are failing after picking your last commit, mind having a look?

**Review by tchaton — APPROVED** [review]
LGTM !

**Pull request merged**
