### PR TITLE
Weekly patch release v1.7.7

### PR DESCRIPTION
**Pull request by kaushikb11**
## What does this PR do?

```
gh pr list -s merged -S 'merged:2022-09-13T22:00:00.000Z..2022-09-21T22:00:00.000Z' --json mergedAt,milestone,url,mergeCommit,title --jq 'sort_by(.mergedAt) | reverse | .[] | select((.milestone.title == "pl:1.7.x") or (.milestone.title == null) or (.milestone.title == "all:next")) | [.url, .mergeCommit.oid, .title] | join(" ")' --limit 100

https://github.com/Lightning-AI/lightning/pull/14809 ac5e0b3bd9f7efb00c8e2d42413616c132db5530 Fixed `TypeError` on 1.7.6 when `torch.distributed` unavailable
https://github.com/Lightning-AI/lightning/pull/14787 326e5afafd35ab89545a739a347a5d8db27cec81 Update pandas requirement from <=1.4.3,>1.0 to >1.0,<1.5.1 in /requirements
https://github.com/Lightning-AI/lightning/pull/14794 f167d7650858b1a3c2689cb4f8385236f8fc6144 Update hpu-tests.yml to support v1.6.0 release
https://github.com/Lightning-AI/lightning/pull/14771 12bae9b7f5585ff22836e1665b3f3a563f90b60a Update wandb requirement from <0.13.2,>=0.10.22 to >=0.10.22,<0.13.4 in /requirements
https://github.com/Lightning-AI/lightning/pull/14714 39f899a80cb1118431576838cd3f86ead01404ff Fix neptune-client package available detection
https://github.com/Lightning-AI/lightning/pull/14762 4f9c7793e754545366796e041fe431d1e9e646a2 Fix TensorBoardLogger creating redundant experiment when finalizing
https://github.com/Lightning-AI/lightning/pull/14752 d9be959bc22b9c5fa4c5225370223eca75e27718 fix: keep pre versions
https://github.com/Lightning-AI/lightning/pull/14750 ced94874b28a0d5206b1a845b9833d7e6b32ea86 Use valid pypi versions for install in assistant
https://github.com/Lightning-AI/lightning/pull/14744 fbb7177e5f86948773ab05f423b19727183f208d Combine the pip install commands in conda workflow
https://github.com/Lightning-AI/lightning/pull/14718 57ae32783ab1967549d9f2cabdc01d12cb545f94 update codeowners
https://github.com/Lightning-AI/lightning/pull/14730 4f88014cc5d19e395d93afcde1f7c53fa0b958ef Docs: fix link to title
https://github.com/Lightning-AI/lightning/pull/14724 5ff78f0753c6ac030b344fd985cf21ec8dc3b47f Use the setter in the children recursively
https://github.com/Lightning-AI/lightning/pull/14671 f3736f642a2871b4ee39716b618a6d96fbcdfeb2 Update ipython[all] requirement from <8.4.1 to <8.5.1 in /requirements
https://github.com/Lightning-AI/lightning/pull/14656 bc9dd1fb2a87085bb31f465f2a749515e1858459 Break hpu graphs into two for better performance
```

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @tchaton @rohitgr7 @borda @akihironitta

### CODE REVIEW

**Comment by kaushikb11** [comment]
Waiting for #14821 to get in

**Comment by awaelchli** [comment]
I agree that #14708 is too hard to include and is not worth it. It would be good if you could drop the commit completely instead of having a reverting one. Also not sure why there are merge commits, these should be avoided. 

Furthermore:
- Needs to update the release date in changelog title
- Package version bump in `__version__.py` 

Otherwise LGTM.

**Comment by awaelchli** [comment]
If there's still room, I can cherry pick #14822.

**Comment by carmocca** [comment]
@awaelchli I addressed your comments but did not cherry-pick #14822. It would need to be completely re-done for this branch as the original targets the new lite code.

**Review by carmocca — APPROVED** [review]

**Review by awaelchli — APPROVED** [review]

**Review by otaj — APPROVED** [review]

**Review by Borda — APPROVED** [review]

**Pull request merged**
