### PR TITLE
Organize model summary utilities

### PR DESCRIPTION
**Pull request by awaelchli**
## What does this PR do?

Applies my delayed review comment https://github.com/Lightning-AI/lightning/pull/13427#discussion_r910102339

> for organisation, it would be nice if it was called model_summary_deepspeed or if it was grouped under a folder model_summary

### Does your PR introduce any breaking changes? If yes, please list them.

No, the imports for the existing model summary public methods and classes remain backward compatible. 
The only changes are for the deepspeed related parts that have not been released yet. 

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- [x] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?
I made sure I had fun coding 🙃

cc @borda @justusschock @awaelchli @rohitgr7 @kaushikb11 @akihironitta

### CODE REVIEW

**Comment by carmocca** [comment]
> The only changes are for the deepspeed related parts that have not been released yet.

This will only be true if it's merged before the release

**Review by kaushikb11 — APPROVED** [review]

**Comment by awaelchli** [comment]
That's my intention. I strongly suggest to merge this in 1.7 otherwise we have 1) inconsistent naming of modules 2) have to go through the entire dep cycle to rename it :))

**Comment by carmocca** [comment]
@awaelchli Can you fix the conflicts? Thanks

**Review by tchaton — APPROVED** [review]
LGTM !

**Pull request merged**
