### PR TITLE
[wip] CI: Define reusable workflows

### PR DESCRIPTION
**Pull request by akihironitta**
## What does this PR do?
Part of #12545. Defines the following reusable workflows to be used across different projects in the future.
```
_check-code.yml
_check-docs.yml
_check-package.yml
_check-schema.yml
```

I used the word `check` to differentiate these from the package testing workflows, such as `ci_test-{full,slow,conda}`, but open for suggestions :]

---

### TODO
Still testing out these reusable workflows in other repos so that we don't need to update these later again:

- [ ] https://github.com/PyTorchLightning/metrics/tree/ci/try-reusable-workflows
- [ ] (not created yet) https://github.com/PyTorchLightning/lightning-flash/tree/ci/try-reusable-workflows
- [ ] (not created yet) https://github.com/PyTorchLightning/lightning-tutorials/tree/ci/try-reusable-workflows
- [ ] (not created yet) https://github.com/PyTorchLightning/lightning-transformers/tree/ci/try-reusable-workflows
- [ ] https://github.com/PyTorchLightning/lightning-bolts/tree/ci/try-reusable-workflows

### Does your PR introduce any breaking changes? If yes, please list them.
None

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [n/a] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @carmocca @akihironitta @borda

### CODE REVIEW

**Review by carmocca — COMMENTED** [review]
Where exactly do you want to reuse these check steps?

**Comment by akihironitta** [comment]
I'll have this PR on hold since there may be other restructuring planned for LAI in CI and that'll make me do rebase again and again.

**Comment by carmocca** [comment]
@akihironitta What's the status here?

**Comment by akihironitta** [comment]
This is being worked on in another repository (https://github.com/Lightning-AI/devtools), so this PR can now be closed.

**Pull request closed without merging**
