### PR TITLE
Remove the `HivemindStrategy`

### PR DESCRIPTION
**Pull request by carmocca**
## What does this PR do?

Removes the `HivemindStrategy()`

The code for this strategy is conveniently self-contained. We will move the implementation to a separate repository (TBD) which tests support with newer PL versions.

Related #16183 (to be transferred) 

### Does your PR introduce any breaking changes? If yes, please list them.

Removes the `HivemindStrategy()`

cc @justusschock @awaelchli @borda

### CODE REVIEW

**Review by awaelchli — APPROVED** [review]

**Review by justusschock — APPROVED** [review]
I vote for moving it in a separate repository as it is the only thing we have that supports training on heterogeneous clusters of variable sizes (spot instances).

**Comment by awaelchli** [comment]
In addition to @justusschock suggestion, this could also make a great tutorial how to build a custom strategy, integrating a library like this, perhaps in the context of Fabric.

**Comment by Borda** [comment]
> I vote for moving it in a separate repository as it is the only thing we have that supports training on heterogeneous clusters of variable sizes (spot instances).

I think that shall be for the time being preserved in separate repo

**Comment by lantiga** [comment]
I also vote for moving it out (and having it in ecosystem-ci), and second @awaelchli 's suggestion about demonstrating how to maintain a strategy for others that will want/need to do it.

**Pull request merged**
