### PR TITLE
Removes BYOC from LAI docs site

### PR DESCRIPTION
**Pull request by Felonious-Spellfire**
## What does this PR do?

Removes BYOC content from LAI site 

### Does your PR introduce any breaking changes? If yes, please list them.

None

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [X] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [X] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @borda @rohitgr7

### CODE REVIEW

**Review by Borda — CHANGES_REQUESTED** [review]
Why remove it when it is going to be added with the next release?

**Comment by Felonious-Spellfire** [comment]
> Why remove it when it is going to be added with the next release?

The content needs to be merged after/as the feature is available

**Comment by Borda** [comment]
> > Why remove it when it is going to be added with the next release?
> 
> The content needs to be merged after/as the feature is available

but it is already on master, see #13835 #13894

**Comment by awaelchli** [comment]
@Felonious-Spellfire We normally have the docs together with the feature development. The docs people see when going to our page are routing to `https://pytorch-lightning.readthedocs.io/en/stable/` (note stable at the end), which means they see the docs that were published up to the newest release. They don't see what we have here on the development branch unless actively navigating to `https://pytorch-lightning.readthedocs.io/en/latest`. I think it is important that we develop the docs together with the features and don't hold back until last minute to add them.

**Comment by Borda** [comment]
> @Felonious-Spellfire We normally have the docs together with the feature development. The docs people see when going to our page are routing to `https://pytorch-lightning.readthedocs.io/en/stable/` (note stable at the end), which means they see the docs that were published up to the newest release. They don't see what we have here on the development branch unless actively navigating to `https://pytorch-lightning.readthedocs.io/en/latest`. I think it is important that we develop the docs together with the features and don't hold back until last minute to add them.

The problem here is that App/LAI has only the latest docs till now... see the proposed changes in #14312 and #14250

**Comment by awaelchli** [comment]
Okay, that's fine with me. Hopefully this can change soon. It is really crucial that new features get reviewed and tested together with the docs present.

**Pull request closed without merging**
