### PR TITLE
Add `@override` for subclasses of PyTorch `Strategy`

### PR DESCRIPTION
**Pull request by VictorPrins**
## What does this PR do?

It adds the `@override` decorator for all subclasses of `lightning.pytorch.strategies.strategy.Strategy` (#18695).

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

----
:books: Documentation preview :books:: https://pytorch-lightning--18911.org.readthedocs.build/en/18911/

### CODE REVIEW

**Comment by VictorPrins** [comment]
cc @carmocca Could you please approve the workflows of this PR?

**Comment by VictorPrins** [comment]
There are 5 failing checks:

- the 3 checks `pl-cpu (<os>, lightning, 3.8, 1.12, oldest)` due to a dependency conflict: `typing-extensions ==4.4.0 and ==4.0.0`.
- [`pl-cpu (macOS-12, pytorch, 3.11, 2.1)`](https://github.com/Lightning-AI/lightning/actions/runs/6721326936/job/18267102110?pr=18911)
- [Pytorch docs linkcheck ](https://github.com/Lightning-AI/lightning/actions/runs/6721326928/job/18267097754?pr=18911#logs)

How should these errors be handled? @awaelchli @carmocca

**Comment by awaelchli** [comment]
@VictorPrins We will handle the unrelated/flaky CI failures, no worries.

**Comment by carmocca** [comment]
I'll try to bump the version in https://github.com/Lightning-AI/lightning/pull/18916. Doing so should unblock this

**Review by carmocca — APPROVED** [review]
LGTM!

**Comment by VictorPrins** [comment]
cc @awaelchli this is ready for merge.

**Comment by VictorPrins** [comment]
cc @awaelchli This is ready to go

**Review by awaelchli — APPROVED** [review]

**Pull request merged**
