### PR TITLE
Add `pip` dependency to resolve hanging `custom_work_dependency` test

### PR DESCRIPTION
**Pull request by otaj**
Hopefully resolves hang happening in `custom_work_dependency` test, that is blocking app framework.

The related issue https://github.com/pypa/pip/issues/11387
cc @carmocca @akihironitta @borda @manskx

### CODE REVIEW

**Review by awaelchli — APPROVED** [review]

**Comment by akihironitta** [comment]
Is this PR a patch for #15417? If so, it's just been fixed by #15431. See its CI run in master: https://dev.azure.com/Lightning-AI/lightning/_build/results?buildId=111417&view=results

**Comment by Borda** [comment]
I think that #15431 was a hotfix to unblock the master but not addressing the underlying issue...

**Comment by justusschock** [comment]
@akihironitta mind checking this PR if it is still relevant? Would greatly appreciate if you could take it over or just close it.

**Comment by akihironitta** [comment]
Closing this PR as the reason for the hang was because of the very outdated docker image used in CI as I confimed with Mansy last week in #15417.

**Pull request closed without merging**
