### PR TITLE
Make delimiter in rich progress bar configurable

### LINKED ISSUE #18366: Inefficiency in Rich Progress bar
### Description & Motivation

* The render method in lightning.pytorch.callbacks.progress.rich_progress.py (lines 170-172) currently uses string concatenation within a loop. 
* Given that the render method is called frequently, this inefficient approach can significantly impact performance.

```python
text = ""
for k, v in self._metrics.items():
    text += f"{k}: {round(v, 3) if isinstance(v, float) else v} "
return Text(text, justify="left", style=self._style)
```

### Pitch

I want to use the str.join method for creating the rendered text, as recommended by the Python documentation. 

Optionally, I would want to introduce the option for the user to see the metrics on separate lines. This could be achieved by using a different joining delimiter: e.g. "\n".join vs "".join.

### Alternatives

_No response_

### Additional context

* Python's string objects are immutable. Therefore, every string concatenation creates a new string object.
* Frequent string concatenations, especially inside loops, can lead to inefficiencies.
* [Python docs](https://docs.python.org/3/library/stdtypes.html#str): There is also no mutable string type, but [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [io.StringIO](https://docs.python.org/3/library/io.html#io.StringIO) can be used to efficiently construct strings from multiple fragments.

cc @borda

### PR DESCRIPTION
**Pull request by quintenroets**
## What does this PR do?

Fixes #18366

Enables configurable delimiter in the metrics display column of the rich progress bar

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

### CODE REVIEW

**Review by awaelchli — APPROVED** [review]
LGTM. Could you also add a changelog entry? (in src/lightning/pytorch/CHANGELOG.md)

**Review by carmocca — APPROVED** [review]

**Review by Borda — APPROVED** [review]

**Comment by quintenroets** [comment]
> LGTM. Could you also add a changelog entry? (in src/lightning/pytorch/CHANGELOG.md)

Should I make a new PR for this?

**Comment by awaelchli** [comment]
No worries, this isn't a critical thing. We will include the update [in one of the next PRs](https://github.com/Lightning-AI/lightning/pull/18385/commits/604c32ace42f7915dbbc9434ccfccb8ed5f18221). 

Thanks a lot for your contributions.

**Comment by quintenroets** [comment]
> No worries, this isn't a critical thing. We will include the update [in one of the next PRs](https://github.com/Lightning-AI/lightning/pull/18385/commits/604c32ace42f7915dbbc9434ccfccb8ed5f18221).
> 
> Thanks a lot for your contributions.

Okay, perfect! Thank you for helping me and giving me the opportunity to contribute.

**Pull request merged**
