### PR TITLE
Redirect users from neptune-client to the neptune package

### LINKED ISSUE #18555: cannot find neptune.new.utils with `Neptune-client==0.16.3`
### Bug description

Pytorch Lightning 2.0.8 - `import pytorch_lightning as pl` fails with error message `No module named 'neptune.new.utils'`, but I have Neptune-client 0.16.3. More interestingly, the code runs perfectly on an env that does not even have neptune-client installed.
I have reproduced on a clean environment (see steps below), and I was able to import Lightning up until the point where I installed Neptune-client. Then, the import fails with the error message presented here.
My problem is that I need to use Lightning in an env a customer provided us, which uses Neptune-client as indicated, and I am therefore unsure on whether we can remove/change that package.
This is on Python 3.10.12.

Error traceback:
```
ModuleNotFoundError                       Traceback (most recent call last)
File [main.py] in line 7
      1 #%%
      2 # basic libraries
      3 #import  os
      4 #import  yaml
      5 
      6 # pytorch lightning
----> 7 import  pytorch_lightning           as      pl
      8 from    lightning.pytorch           import  Trainer
      9 from    lightning.pytorch.loggers   import  TensorBoardLogger

File [~/miniforge3/envs/test_env/lib/python3.10/site-packages/pytorch_lightning/__init__.py:26]
     23     _logger.propagate = False
     25 from lightning_fabric.utilities.seed import seed_everything  # noqa: E402
---> 26 from pytorch_lightning.callbacks import Callback  # noqa: E402
     27 from pytorch_lightning.core import LightningDataModule, LightningModule  # noqa: E402
     28 from pytorch_lightning.trainer import Trainer  # noqa: E402

File [~/miniforge3/envs/test_env/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py:29]
     27 from pytorch_lightning.callbacks.prediction_writer import BasePredictionWriter
     28 from pytorch_lightning.callbacks.progress import ProgressBar, RichProgressBar, TQDMProgressBar
---> 29 from pytorch_lightning.callbacks.pruning import ModelPruning
     30 from pytorch_lightning.callbacks.rich_model_summary import RichModelSummary
...
     56 else:
     57     # needed for tests, mocks and function signatures
     58     neptune, Run, Handler, File, stringify_unsupported = None, None, None, None, None

ModuleNotFoundError: No module named 'neptune.new.utils'
```

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

Create new environment
```
conda create -n test_env
```

Install Pytorch 1.11.0
```
conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 -c pytorch
```

Install Pytorch Geometric (the one for Pytorch 1.11)
```
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.11.0+cpu.html
```

Install Pytorch Lightning (note that lightning 2.0 is compatible with Pytorch 1.11, see compatibility matrix https://lightning.ai/docs/pytorch/stable/versioning.html)
```
python -m pip install lightning
```

Install neptune-client 0.16.3
```
pip install neptune-client==0.16.3
```

Try importing Pytorch Lightning
```
import pytorch_lightning as pl
```

Obtain error message above.
```



### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version: 2.0.8
#- PyTorch Version: 1.11.0
#- Python version: 3.10.12
#- OS: McOS Ventura 13.4.1
```

</details>


cc @Blaizzy

### PR DESCRIPTION
**Pull request by awaelchli**
## What does this PR do?

Fixes #18555
TODO verify with neptune team.

----
:books: Documentation preview :books:: https://pytorch-lightning--18558.org.readthedocs.build/en/18558/

### CODE REVIEW

**Comment by awaelchli** [comment]
Hey @Blaizzy 
Do these changes to the neptune imports look good to you? Or is it too early to make this change?

**Comment by Blaizzy** [comment]
Hey 

These look great 👍🏽

**Comment by Blaizzy** [comment]
cc: @SiddhantSadangi

**Comment by SiddhantSadangi** [comment]
@awaelchli - We are still supporting `neptune-client`, so these changes would be a bit too early.

Responded to #18555 here: https://github.com/Lightning-AI/lightning/issues/18555#issuecomment-1721216339

**Pull request closed without merging**
