### PR TITLE
Cherry pick to app release branch (app v0.5.6)

### PR DESCRIPTION
**Pull request by rlizzo**
## What does this PR do?

patch release to update `lightning-cloud` version to `0.5.3`

### Does your PR introduce any breaking changes? If yes, please list them.

No

cc @tchaton @rohitgr7 @borda

### CODE REVIEW

**Comment by Borda** [comment]
@rlizzo is it intentional to bring up just 1/2 of this feature? #14002

**Review by Borda — APPROVED** [review]

**Comment by manskx** [comment]
Seems to be an issue with the e2e tests, let's fix it first.

**Review by manskx — APPROVED** [review]

**Review by awaelchli — APPROVED** [review]

**Comment by Borda** [comment]
@manskx, any progress on the failing Win tests?

**Comment by manskx** [comment]
> @manskx, any progress on the failing Win tests?

@Borda not yet.

**Comment by Borda** [comment]
> > @manskx, any progress on the failing Win tests?
> 
> @Borda not yet. You mean the e2e tests right ?

Anything needed to be safe with this release =)

**Pull request merged**
