### PR TITLE
Prefer `log_dir` when using CSVLogger

### LINKED ISSUE #17168: SaveConfigCallback saves config to the current working directory instead of the logging directory.
### Bug description

According to the doc, `SaveConfigCallback` should save config files to dynamic logging directories like `lightning_logs/version_7/config.yaml` by default, but it seems like it just saves to the current working directory, which is the default `trainer.log_dir`.

### How to reproduce the bug

```python
# main.py
from pytorch_lightning.cli import LightningCLI
from pytorch_lightning.demos.boring_classes import BoringModel, BoringDataModule


def main():
    LightningCLI(BoringModel, BoringDataModule)


if __name__ == "__main__":
    main()
```

```bash
python main.py fit
```

You'll notice that a `config.yaml` is created in the current working directory rather than the log directory.

### Error messages and logs

_No response_

### Environment

<details>
  <summary>Current environment</summary>

```
* CUDA:
        - GPU:
                - NVIDIA GeForce GTX 1060 6GB
        - available:         True
        - version:           11.7
* Lightning:
        - lightning-utilities: 0.8.0
        - pytorch-lightning: 2.0.0
        - torch:             2.0.0
        - torchmetrics:      0.11.4
* Packages:
        - aiohttp:           3.8.4
        - aiosignal:         1.3.1
        - async-timeout:     4.0.2
        - attrs:             22.2.0
        - certifi:           2022.12.7
        - charset-normalizer: 3.1.0
        - cmake:             3.26.0
        - docstring-parser:  0.15
        - filelock:          3.10.0
        - frozenlist:        1.3.3
        - fsspec:            2023.3.0
        - idna:              3.4
        - importlib-resources: 5.12.0
        - jinja2:            3.1.2
        - jsonargparse:      4.20.0
        - lightning-utilities: 0.8.0
        - lit:               16.0.0
        - markupsafe:        2.1.2
        - mpmath:            1.3.0
        - multidict:         6.0.4
        - networkx:          3.0
        - numpy:             1.24.2
        - nvidia-cublas-cu11: 11.10.3.66
        - nvidia-cuda-cupti-cu11: 11.7.101
        - nvidia-cuda-nvrtc-cu11: 11.7.99
        - nvidia-cuda-runtime-cu11: 11.7.99
        - nvidia-cudnn-cu11: 8.5.0.96
        - nvidia-cufft-cu11: 10.9.0.58
        - nvidia-curand-cu11: 10.2.10.91
        - nvidia-cusolver-cu11: 11.4.0.1
        - nvidia-cusparse-cu11: 11.7.4.91
        - nvidia-nccl-cu11:  2.14.3
        - nvidia-nvtx-cu11:  11.7.91
        - packaging:         23.0
        - pip:               23.0.1
        - pytorch-lightning: 2.0.0
        - pyyaml:            6.0
        - requests:          2.28.2
        - setuptools:        67.4.0
        - sympy:             1.11.1
        - tdgu:              0.1.0
        - torch:             2.0.0
        - torchmetrics:      0.11.4
        - tqdm:              4.65.0
        - triton:            2.0.0
        - typeshed-client:   2.2.0
        - typing-extensions: 4.5.0
        - urllib3:           1.26.15
        - wheel:             0.38.4
        - yarl:              1.8.2
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.10.10
        - version:           #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022
```

</details>

### More info

_No response_

cc @carmocca @mauvilsa @borda

### PR DESCRIPTION
**Pull request by tshu-w**
## What does this PR do?

Fixes #17168 partly (with `CSVLogger`)

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

### CODE REVIEW

**Review by Borda — APPROVED** [review]

**Comment by justusschock** [comment]
Tbh, I'd prefer to solve this as a whole since otherwise we might get different behaviors based on the selected logger which is even worse IMO

**Comment by tshu-w** [comment]
> Tbh, I'd prefer to solve this as a whole since otherwise we might get different behaviors based on the selected logger which is even worse IMO

This is a tricky issue that has been pending for a long time, see https://github.com/Lightning-AI/lightning/issues/14188 and https://github.com/Lightning-AI/lightning/pull/14640, so I want to first solve the built-in logger.

**Comment by tshu-w** [comment]
@justusschock @awaelchli @carmocca @tchaton Hi, any idea on this small PR? ;)

**Comment by awaelchli** [comment]
Fixed in https://github.com/Lightning-AI/lightning/pull/17174
See https://github.com/Lightning-AI/lightning/issues/18547#issuecomment-1728562441

**Pull request closed without merging**
