### PR TITLE
Fix incorrect imports in lightning docs

### PR DESCRIPTION
**Pull request by krishnakalyan3**
## What does this PR do?
This PR fixes incorrect imports 
from `L.frontend.web.StaticWebFrontend`
to `L.app.frontend.StaticWebFrontend`

Looks like I was wrong the way to go now is 
`from lightning_app.frontend import StaticWebFrontend`

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc: @Felonious-Spellfire , @Borda

### CODE REVIEW

**Review by Borda — APPROVED** [review]
Can we have these also testes? :)

**Comment by krishnakalyan3** [comment]
@Borda you mean doc tests?

**Comment by krishnakalyan3** [comment]
Can someone please confirm if this change works with `lightning 0.6.0`

image

For some reason, this seems to be broken for me after upgdating lightning.

**Comment by awaelchli** [comment]
This works fine for me on master, so it must be an issue with the meta packaging. The changes to the imports in this PR are correct, so I would still move forward with this PR and fix any issues related to installation separately. Thanks for trying this out.

**Comment by awaelchli** [comment]
@krishnakalyan3  Here: https://github.com/Lightning-AI/lightning/issues/14683

**Comment by krishnakalyan3** [comment]
@awaelchli thanks!

**Pull request merged**
