### PR TITLE
Fix mypy errors attributed to pytorch_lightning/profilers/base.py

### PR DESCRIPTION
**Pull request by LeeChanHyuk**
## What does this PR do?

Fixes mypy typing errors in pytorch_lightning/profilers/base.py in https://github.com/Lightning-AI/lightning/issues/13445.

**[Mypy error]**
```python
src/pytorch_lightning/profilers/base.py:60: error: Function is missing a type annotation  [no-untyped-def]
```

### Does your PR introduce any breaking changes? If yes, please list them.

None

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

I had fun doing this contribution. Thank you.

### CODE REVIEW

**Comment by otaj** [comment]
Hi @LeeChanHyuk. Thank you for your PR. However, you're not supposed to run `mypy <file>` but only `mypy` - the difference is that the latter takes into account whole codebase and not only things imported by the particular file.

When run like this on master branch with `"pytorch_lightning.profilers.base"` commented out from `pyproject.toml`, only one error pops up

```
src/pytorch_lightning/profilers/base.py:60: error: Function is missing a type annotation  [no-untyped-def]
Found 1 errors in 1 file (checked 240 source files)
```

The reference check is the one happening on our CI, there you can see the errors

**Review by otaj — CHANGES_REQUESTED** [review]
Hi @LeeChanHyuk. Thank you for your PR. However, you're not supposed to run `mypy <file>` but only `mypy` - the difference is that the latter takes into account whole codebase and not only things imported by the particular file.

When run like this on master branch with `"pytorch_lightning.profilers.base"` commented out from `pyproject.toml`, only one error pops up

```
src/pytorch_lightning/profilers/base.py:60: error: Function is missing a type annotation  [no-untyped-def]
Found 1 errors in 1 file (checked 240 source files)
```

The reference check is the one happening on our CI, there you can see the errors

**Comment by LeeChanHyuk** [comment]
> Hi @LeeChanHyuk. Thank you for your PR. However, you're not supposed to run `mypy <file>` but only `mypy` - the difference is that the latter takes into account whole codebase and not only things imported by the particular file.
> 
> When run like this on master branch with `"pytorch_lightning.profilers.base"` commented out from `pyproject.toml`, only one error pops up
> 
> ```
> src/pytorch_lightning/profilers/base.py:60: error: Function is missing a type annotation  [no-untyped-def]
> Found 1 errors in 1 file (checked 240 source files)
> ```
> 
> The reference check is the one happening on our CI, there you can see the errors

@otaj 
Thank you for your kind comment.
I followed your instruction for mypy, but I got the test errors on my code.
I am a beginner at this task, so could you please tell me what should I do to fix the test error?
Thank you.

**Comment by otaj** [comment]
@LeeChanHyuk, no worries about being a beginner, we all started somehow :purple_heart: 

First of all, the error would be solved perfectly fine if you did this:
```python
def __init__(self, *args: Any, **kwargs: Any):
    ...
```

However! Since I have not been taking too hard of a look at particular pieces of code that should be fixed in the typing issue before, I just now realized, that we can safely close this PR. If you take a look, this class (`BaseProfiler`) is deprecated and will be removed in 1.8 release - but we have a 1.7 release on Monday and right after the release, we can remove all the things that are scheduled to be removed in 1.8 release. I'm sorry about assigning this work when the parts of code are deprecated, I didn't notice it.

So, I am closing this PR for now, and on Monday, right after 1.7 release, there will be a call for action for removing features scheduled to be removed in 1.8. Please, sign up there.

Thank you for your contribution :zap:

**Pull request closed without merging**
