### PR TITLE
CI: drop unused tests

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

These tests are not called or used anywhere...

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @carmocca @akihironitta @borda

### CODE REVIEW

**Review by carmocca — APPROVED** [review]
cc @nicolai86 as this was discussed in https://github.com/Lightning-AI/lightning/pull/13835#discussion_r943670273

**Comment by awaelchli** [comment]
@carmocca They probably run in the internal repo. @nicolai86 can you confirm? So let's move the tests there?

**Comment by Borda** [comment]
> @carmocca They probably run in the internal repo. @nicolai86 can you confirm? So let's move the tests there?

in such a case what it is here and not internal? :D
spoke with @manskx and he mentioned it is not used anywhere...

**Review by akihironitta — APPROVED** [review]

**Review by nicolai86 — APPROVED** [review]
I ran these as I was working on the BYOC cli.
We'll have to shift that to the platform repository soon so let's get rid of it here.

**Review by awaelchli — APPROVED** [review]

**Comment by awaelchli** [comment]
Thanks for the clarification @nicolai86!

**Pull request merged**
