### PR TITLE
[App] Fix `AutoScaler` example

### LINKED ISSUE #16555: ZeroDivisionError error with AutoScaler
### Bug description

Getting ZeroDivisionError while running the AutoScaler example

### How to reproduce the bug

```python
1. clone lightning
2. goto examples [app_server_with_autoscaler](https://github.com/Lightning-AI/lightning/blob/879701f52fda7e0d0cb9a7fe6446838356085af5/examples/app_server_with_auto_scaler/app.py#L70)
3. run `lightning run app app.py`
```

### Error messages and logs

```
Traceback (most recent call last):
  File "/Users/aniket/miniconda3/envs/lit/bin/lightning", line 8, in <module>
    sys.exit(main())
  File "/Users/aniket/Projects/github/lightning/src/lightning/app/cli/lightning_cli.py", line 105, in main
    _main()
  File "/Users/aniket/miniconda3/envs/lit/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aniket/miniconda3/envs/lit/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/aniket/Projects/github/lightning/src/lightning/app/utilities/exceptions.py", line 36, in invoke
    return super().invoke(ctx)
  File "/Users/aniket/miniconda3/envs/lit/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aniket/miniconda3/envs/lit/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aniket/miniconda3/envs/lit/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aniket/miniconda3/envs/lit/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/aniket/Projects/github/lightning/src/lightning/app/cli/lightning_cli.py", line 376, in run_app
    _run_app(
  File "/Users/aniket/Projects/github/lightning/src/lightning/app/cli/lightning_cli.py", line 295, in _run_app
    dispatch(
  File "/Users/aniket/Projects/github/lightning/src/lightning/app/runners/runtime.py", line 102, in dispatch
    return runtime.dispatch(open_ui=open_ui, name=name, no_cache=no_cache, cluster_id=cluster_id)
  File "/Users/aniket/Projects/github/lightning/src/lightning/app/runners/multiprocess.py", line 127, in dispatch
    self.app._run()
  File "/Users/aniket/Projects/github/lightning/src/lightning/app/core/app.py", line 524, in _run
    done = self.run_once()
  File "/Users/aniket/Projects/github/lightning/src/lightning/app/core/app.py", line 469, in run_once
    self.root.run()
  File "/Users/aniket/Projects/github/lightning/src/lightning/app/components/serve/auto_scaler.py", line 651, in run
    self.autoscale()
  File "/Users/aniket/Projects/github/lightning/src/lightning/app/components/serve/auto_scaler.py", line 710, in autoscale
    min(self.max_replicas, self.scale(self.num_replicas, metrics)),
  File "app.py", line 57, in scale
    pending_requests_per_work = metrics["pending_requests"] / (replicas + metrics["pending_works"])
ZeroDivisionError: division by zero
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

### More info

_No response_

### PR DESCRIPTION
**Pull request by akihironitta**
## What does this PR do?
Fixes #16555.

### Does your PR introduce any breaking changes? If yes, please list them.
None

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @borda

### CODE REVIEW

**Comment by akihironitta** [comment]
@aniketmaurya Can you give this a try when you get a chance?

**Review by awaelchli — APPROVED** [review]
Milestone is missing

**Review by Borda — APPROVED** [review]
btw, do we have it tested?

**Review by tchaton — APPROVED** [review]
LGTM ! Mind adding a test ?

**Pull request merged**
