### PR TITLE
Update docs with new Lightning Lite usage 1/n

### PR DESCRIPTION
**Pull request by awaelchli**
## What does this PR do?

We introduced a new way to interact with Lightning Lite in #14992. The `run` method approach is no longer the recommended way moving forward. 

This first PR focuses on
- Updates to remove subclassing LightningLite in example code
- self.x -> lite.x
- Usage of the CLI

Future PRs will need to
- Add section on how to run in Jupyter notebook
- Update the animated GIF

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- [x] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?
I made sure I had fun coding 🙃

cc @borda @carmocca @justusschock @awaelchli

### CODE REVIEW

**Review by carmocca — COMMENTED** [review]
This effectively forces us to release lite on the next minor release. It would be weird to have it in the docs if we are going to have large breaking changes by changing the names. Is this agreed on?

**Comment by Borda** [comment]
cc: @lantiga

**Comment by awaelchli** [comment]
This PR doesn't change any names or breaks APIs. I'm updating the docs based on what we have in master. Old code will still work. I am quite confused about what the issue here is. Where would you expect this documentation to show up if not here?

**Comment by carmocca** [comment]
I'm just saying that since this PR changes the docs to use the new package and imports, then whoever is reading the docs will see this. Right now it's only on the "latest" docs, but not anymore after we make a 1.x release which means that it would be messy to change names after that. This is also related to the motivation in https://github.com/Lightning-AI/lightning/pull/15586#issuecomment-1308818630

**Comment by awaelchli** [comment]
Reverted the link changes. Now still points to :class:~pytorch_lightning.lite.LightningLite

**Review by yurijmikhalevich — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
LGTM !

**Pull request merged**
