### PR TITLE
Weekly Patch Release v1.9.2

### PR DESCRIPTION
**Pull request by awaelchli**
## What does this PR do?

How to get your commit released:
1. Set the milestone on your PR to 1.9.x
2. git checkout 1-9-2-draft
3. git cherry-pick [your commit]
4. Resolve conflicts (warning - the package structure has severely diverged from master)
5. git push
6. Make sure that tests pass, so that the next person can cherry pick their changes

List all commits:

```bash
 gh pr list -s merged -S 'merged:2023-02-09T19:30:00.000Z..2023-02-20T12:00:00.000Z' --json mergedAt,milestone,url,mergeCommit,title --jq 'sort_by(.mergedAt) | reverse | .[] | select((.milestone.title == null) or (.milestone.title == "v1.9.x")) | [.url, .mergeCommit.oid, .title] | join(" ")' --limit 500
```

Previous Release (1.9.1): #16667

cc @borda @carmocca @akihironitta @justusschock @awaelchli

### CODE REVIEW

**Comment by carmocca** [comment]
If you want to include it, https://github.com/Lightning-AI/lightning/pull/16365 is marked as 1.9.x but was not cherry-picked.

**Comment by Borda** [comment]
> If you want to include it, #16365 is marked as 1.9.x but was not cherry-picked.

It is a change not a fix so maybe rather leave it out...

**Comment by awaelchli** [comment]
Note: The IPU job fails for the same reason as in #16667

**Comment by Borda** [comment]
fyi, @luca3rd mentioned he would like to get in some CLI features...

**Review by Borda — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
LGTM !

**Review by akihironitta — APPROVED** [review]

**Pull request merged**
