### PR TITLE
Set default `name` and `save_dir` for `WandbLogger`

### LINKED ISSUE #12036: Several issues with `WandbLogger` output directory structure in offline mode
## Proposed refactor

Change the default `name` to "lightning_logs" and the default `save_dir` to "wandb".
https://github.com/PyTorchLightning/pytorch-lightning/blob/60fe1520fd8ac8fa9006237f31045465200c9803/pytorch_lightning/loggers/wandb.py#L252-L253

### Motivation

Currently the `name` and `save_dir` properties on the `WandbLogger` default to `None`, and the version can be `None` as well.  This causes several issues in the directory structure as shown in the image below:

wandb currentl

1. The main logging directory is named `None` which is an odd name for a directory to store logs
2. Wandb already automatically creates a directory called `wandb` which contains metadata. It is weird to have two separate logging directories for Wandb - let's instead default to storing everything in one. Plus, the doc literally says the save_dir is `wandb` by default, which is not true at the moment:
https://github.com/PyTorchLightning/pytorch-lightning/blob/60fe1520fd8ac8fa9006237f31045465200c9803/pytorch_lightning/loggers/wandb.py#L221
3. The profiler output is unable to save to a path since the logger's save_dir is `None`, and we get the error `The PyTorchProfiler failed to export trace as dirpath is None`
4. A fourth issue, but one that is not addressed by this proposed change, is that the subdirectory is named "version_None" which is also an odd name for a directory.

How the directory structure will look after this change:
wandb after

cc @awaelchli @morganmcg1 @AyushExel @borisdayma @scottire @manangoel99

### PR DESCRIPTION
**Pull request by daniellepintz**
## What does this PR do?
Fixes #12036

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by manangoel99** [comment]
Hi @daniellepintz ! I'm an engineer at Weights & Biases. This looks awesome! I have a fix for the `version` issue as well. Would it be alright if I add it to this PR?

**Review by carmocca — APPROVED** [review]

**Comment by daniellepintz** [comment]
@manangoel99 Sure, feel free to add the version fix to this PR!

**Comment by manangoel99** [comment]
@daniellepintz please share your wandb version and pytorch-lightning version

**Comment by daniellepintz** [comment]
@manangoel99 
pytorch-lightning: 1.5.10
wandb: 0.12.10

Here is an example repro in this notebook: https://colab.research.google.com/drive/1uhbawIaU-2VScaDmyKUwtcxzS6twLJ06?usp=sharing

**Comment by manangoel99** [comment]
@daniellepintz I looked at this a little more closely and I found that we need just one small change to fix #12036 . Removing the `version` argument works for fixing all the problems caused by keeping the default values `None`. 

https://github.com/manangoel99/pytorch-lightning/blob/fea68b8390f6899aea6e92a2f875f5c700614c9f/pytorch_lightning/loggers/wandb.py#L255

https://github.com/manangoel99/pytorch-lightning/blob/fea68b8390f6899aea6e92a2f875f5c700614c9f/pytorch_lightning/loggers/wandb.py#L295

Editing these 2 lines should be good enough.

- We can keep the default value of `name` argument as `None` because the name is automatically assigned by wandb whenever a run is initiated so keeping a default value would give the same name to all the runs.
- The project argument if given `None` logs the project automatically into the "uncategorized" project on W&B. This is the default behavior. Hence, if `save_dir == None`, in that case we would get a directory by the name "uncategorized" apart from the "wandb" directory. For reference, this is what the directory structure would look like 
Screenshot 2022-02-24 at 9 12 24 PM

**Comment by awaelchli** [comment]
Perhaps we should first finish  #12604

**Pull request closed without merging**
