### PR TITLE
CI: install more OS

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

adding more OS for install CI

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by carmocca** [comment]
Why not replace the old ones? Do you expect that one would fail and not the other?

**Comment by Borda** [comment]
> Why not replace the old ones?

they are not too old, and people are still using them such as Ubuntu 20.04 is still major

> Do you expect that one would fail and not the other?

don't know, but this is a reaction to @williamFalcon issue last week where he had a problem installing `lightning` on his Apple M1... but probably the issue is related to the new chair arch - AMD not the OS :confused:

**Review by akihironitta — APPROVED** [review]
(ignore me if I'm wrong but) IMHO, variation in the Python version can impact more than in the OS version, so if we really need to extend the coverage, I would start with adding more Python versions.

**Comment by Borda** [comment]
> (ignore me if I'm wrong but) IMHO, variation in the Python version can impact more than in the OS version, so if we really need to extend the coverage, I would start with adding more Python versions.

You are right that the Python version is also important; in such case we can consider adding tests for py3.10 as I would assume that changes are rather liners so testing the min and max version shall be sufficient :otter:

**Comment by carmocca** [comment]
I would rather not add more CI stress (jobs) if they won't provide relevant coverage. As you said:

>  but probably the issue is related to the new chair arch - AMD not the OS

**Comment by williamFalcon** [comment]
pip install lightning is failing on various python versions and machine types… we definitely need tests for this.

**Comment by carmocca** [comment]
My point is that if the current additions (ubuntu-22.04, macOS-12) covered the issue experienced the jobs would be failing. But they aren't meaning they aren't testing anything meaningful at the moment.

**Comment by carmocca** [comment]
We cannot test mac Mx chips because there's no cloud provider, but we can try adding a job for 3.10

**Review by awaelchli — APPROVED** [review]

**Comment by akihironitta** [comment]
> My point is that if the current additions (ubuntu-22.04, macOS-12) covered the issue experienced the jobs would be failing. But they aren't meaning they aren't testing anything meaningful at the moment.

(I approved this change, but) I now totally agree with you.

**Pull request merged**
