### PR TITLE
Remove the graveyard

### PR DESCRIPTION
**Pull request by carmocca**
See title

cc @borda @justusschock @awaelchli

### CODE REVIEW

**Review by justusschock — APPROVED** [review]

**Review by Borda — APPROVED** [review]

**Review by awaelchli — APPROVED** [review]
I'm sure it will come back eventually :

**Comment by carmocca** [comment]
Blocked by https://github.com/Lightning-AI/lightning/pull/16151

**Comment by carmocca** [comment]
There seems to be a test interaction with the legacy checkpoint tests in the `pl-cpu (*, lighting, *, *)` jobs.

It can be reproduced with
```py
pytest checkpointing/test_legacy_checkpoints.py::test_load_legacy_checkpoints[
1.4.9] loops/test_training_loop.py::test_fit_loop_done_log_messages
```

Checkpoints before this version all produce the same error, checkpoints after are fine.

The exact error is a caplog issue

```python
FAILED loops/test_training_loop.py::test_fit_loop_done_log_messages - AssertionError: assert 'should_stop` was set' in ''
```

:cry:

**Comment by awaelchli** [comment]
@carmocca I'm seeing a similar issue with caplog on the exact same three jobs (pl-cpu with 1.13) in https://github.com/Lightning-AI/lightning/pull/16152 😢

**Comment by Borda** [comment]
@carmocca lets merge this. :)

**Comment by carmocca** [comment]
lite/debug is now rebased. Merging this.

**Pull request merged**
