### PR TITLE
Cleaning requirement + git fix

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

Resolving a special case for developers who were affected by #14638 and later fix #14644
Normally clean clone would also help :otter: 
mypy: set connector as skip as a method without proper typing was moved in #14861

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @borda

### CODE REVIEW

**Review by carmocca — APPROVED** [review]

**Review by justusschock — APPROVED** [review]

**Review by krshrimali — APPROVED** [review]

**Review by otaj — APPROVED** [review]

**Comment by awaelchli** [comment]
Maybe @williamFalcon can test this first on his side and then merge the PR if it's good? 
Probably needs to `pip install -e` after pulling that branch, right @Borda?

**Comment by Borda** [comment]
> Maybe @williamFalcon can test this first on his side and then merge the PR if it's good? Probably needs to `pip install -e` after pulling that branch, right @Borda?

there is some problem with using `-e` :/, see: https://github.com/Lightning-AI/lightning/issues/14847#issuecomment-1255106639

**Review by tchaton — APPROVED** [review]
LGTM !

**Comment by williamFalcon** [comment]
@Borda it's broken again...

```
(l1) ➜  lightning git:(master) pip install -e .
Obtaining file:///Users/williamfalcon/Developer/lightning
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "/Users/williamfalcon/opt/miniconda3/envs/l1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/williamfalcon/opt/miniconda3/envs/l1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/williamfalcon/opt/miniconda3/envs/l1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
          return hook(config_settings)
        File "/private/var/folders/78/_1r_8s7d74l4gsgt9w25s0000000gn/T/pip-build-env-_6bjsfp9/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 445, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/private/var/folders/78/_1r_8s7d74l4gsgt9w25s0000000gn/T/pip-build-env-_6bjsfp9/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/78/_1r_8s7d74l4gsgt9w25s0000000gn/T/pip-build-env-_6bjsfp9/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/78/_1r_8s7d74l4gsgt9w25s0000000gn/T/pip-build-env-_6bjsfp9/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 482, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/78/_1r_8s7d74l4gsgt9w25s0000000gn/T/pip-build-env-_6bjsfp9/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 100, in <module>
        File ".actions/setup_tools.py", line 526, in _load_aggregate_requirements
          requires = [
        File ".actions/setup_tools.py", line 527, in <listcomp>
          load_requirements(d, file_name="base.txt", unfreeze=not freeze_requirements)
        File ".actions/setup_tools.py", line 120, in load_requirements
          with open(os.path.join(path_dir, file_name)) as file:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements/docs/base.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(l1) ➜  lightning git:(master) ✗
```

**Comment by otaj** [comment]
@williamFalcon are you on clean master? It seems like you have a directory `requirements/docs`, but no file `requirements/docs/base.txt`. The install script tries to install all the base requirements of all subdirectories present in `requirements` folder.

Btw, I think it should not loudly fail, when such a requirement file is not found, but only warn

**Pull request merged**
