### PR TITLE
CI: simplify groups ref/pointer

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

reduce duplicated sections which are sensitive for human error and improve readability

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Review by akihironitta — APPROVED** [review]
This will be very nice if it works!

**Review by carmocca — CHANGES_REQUESTED** [review]
Blocking until I verify if this works! Thanks for the suggestion

**Comment by Borda** [comment]
> This will be very nice if it works!

in theory, it should, as it is using YAML native directive/syntax

BUT it seems that with this, the referred lists are loaded as sublists, so not expanded as a single flattened list :(
```py
import yaml
yaml.safe_load(".github/checkgroup.yml")
```

**Comment by carmocca** [comment]
I checked and we use https://probot.github.io/api/7.0.1/classes/context.html#config to load the configuration file. There's no mention of any specific parsing constraints so I assume it will work just as `yaml.safe_load()`

Looking at https://stackoverflow.com/questions/24090177/how-to-merge-yaml-arrays, it looks like flattening these list is not possible.

The only solution I can think of is adding support for flattening in the javascript implementation of checkgroup so that we can use this notation: https://github.com/Lightning-AI/probot/blob/babecd77266ed8ac540de7f5e17804030174215c/src/check-group/utils/user_config_parser/populate_subprojects.ts#L63-L91

**Comment by Borda** [comment]
> The only solution I can think of is adding support for flattening in the javascript implementation of checkgroup

Let's keep it simple, personally, it may be food to by default flatten all lists in check and paths as there is no meaning for a tree, but if it is not a few clicks away, let's drop it for now :rabbit:

**Pull request closed without merging**
