### PR TITLE
refactor App examples to `examples/app/`

### LINKED ISSUE #16273: Organize the Examples Folder
### Outline & Motivation

Our examples folder is messy, it currently looks like this: https://github.com/Lightning-AI/lightning/tree/master/examples
It does not matter if you are an expert or a beginner, if you arrive here in this repository, the examples folder sticks out as an obvious place to start exploring. But it's a mess. Where to start? What is important? What is new, what is old? The Readme is outdated. 

### Pitch

Organize the top level folders into:

```
examples/
    app
    fabric
    pytorch
```

Organize the readme, either at the top level or in each subfolder, with sections for

Beginner
Intermediate
Expert

(or a similar structure organized by concepts). 

Delete examples that are too outdated or irrelevant. Make everything as concise as possible.

### Additional context

_No response_

cc @borda @justusschock @awaelchli

### PR DESCRIPTION
**Pull request by aniketmaurya**
## What does this PR do?

Fixes #16273 

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

### CODE REVIEW

**Review by Borda — COMMENTED** [review]
these examples are used in docs and tests, so need to be updated everywhere...

**Comment by awaelchli** [comment]
You can see here #17045 where all the references need to be updated. If you want, you can merge my branch into yours.

**Comment by aniketmaurya** [comment]
> You can see here #17045 where all the references need to be updated. If you want, you can merge my branch into yours.

oops! sorry didn't realize you already had the PR @awaelchli

**Comment by awaelchli** [comment]
Hey @aniketmaurya Yeah thanks and sorry I took this. I wanted to get this done quickly before 2.0 and there were a lot of ci updates and references that had to be fixed to make this work.

**Pull request closed without merging**
