### PR TITLE
Run only CUDA tests on Azure GPU CI

### PR DESCRIPTION
**Pull request by carmocca**
## What does this PR do?

Run only the CUDA tests on Azure GPU CI. Just as we do for TPUs, IPUs, and HPUs CI jobs.
This should slash the runtime considerably.

This logically reduces the coverage as CPU-only code could fail if run on a GPU environment. But this tradeoff is currently worth it given our limitations in GPU testing.

Reduces the "Standard" tests step from GPU ci from ~24' to ~10'

Discussed internally.

### Does your PR introduce any breaking changes? If yes, please list them.

None

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [n/a] Did you make sure to **update the documentation** with your changes? (if necessary)
- [n/a] Did you write any **new necessary tests**? (not for typos and docs)
- [n/a] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [n/a] Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

cc @carmocca @akihironitta @borda

### CODE REVIEW

**Review by rohitgr7 — APPROVED** [review]

**Comment by Borda** [comment]
how about test that is written such uses `max(CPU, GPU)` to reduce code duplication...
in fact, thinking that all tests that are running any form or training shall be exploring both

**Comment by carmocca** [comment]
@Borda Those tests will no longer run if they don't have the `@RunIf(min_cuda_gpus=N)` decorator. I don't think the changes in #13664 are a bad idea but there must be a mechanism to mark which tests run under each configuration. So your PR would become "useless" after this is merged.

**Review by tchaton — APPROVED** [review]
Love it ! This is a great step.

**Review by otaj — APPROVED** [review]

**Comment by Borda** [comment]
> Those tests will no longer run if they don't have the `@RunIf(min_cuda_gpus=N)` decorator. I don't think the changes in #13664 are a bad idea but there must be a mechanism to mark which tests run under each configuration. So your PR would become "useless" CI-wise after this is merged.

I see the motivation for this PR and agree no need to run tests using only CPU on GPU machine but I think that for robustness we shall all push to use instance maximal potential... that is also why @kaushikb11 started #12482 and similar for TPU and IPU...
Said so I do not think this merge is moving anyway towards robust testing... :(

**Comment by carmocca** [comment]
#12482 does exactly what this PR does, but for HPUs. Collect automatically all HPU tests and run them exclusively.

> no need to run tests using only CPU on GPU machine

This is what this PR does

> push to use instance maximal potential

This PR does not go against this idea. It just filters out the jobs that don't require CUDA

**Comment by Borda** [comment]
> This PR does not go against this idea. It just filters out the jobs that don't require CUDA

true, so the way out would be to introduce a flag for tests to run everywhere?

**Comment by carmocca** [comment]
Depends on what we want. For example, we could have a `PL_RUN_ALL_TESTS=1` that nullifies all the other environment variables. But we don't have any job currently where we would need it.

**Comment by Borda** [comment]
> Depends on what we want. For example, we could have a `PL_RUN_ALL_TESTS=1` that nullifies all the other environment variables. But we don't have any job currently where we would need it.

I would do it vise-versa, by default, run all and if some short-run set env variable

**Comment by carmocca** [comment]
Good point: https://github.com/Lightning-AI/lightning/pull/13676

**Pull request merged**
