### PR TITLE
Remove the BaguaStrategy

### PR DESCRIPTION
**Pull request by awaelchli**
## What does this PR do?

[Bagua](https://github.com/BaguaSys/bagua) is unmaintained. The last release it saw was in Jan 2022.

Note: The docker build errors are unrelated to the changes of this PR and will be addressed in #16747

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

cc @borda @carmocca @akihironitta @justusschock @awaelchli @wangraying

### CODE REVIEW

**Review by carmocca — APPROVED** [review]

**Comment by awaelchli** [comment]
The docker build errors are unrelated to the changes of this PR and will be addressed in #16747

**Review by akihironitta — APPROVED** [review]

**Review by Borda — APPROVED** [review]

**Review by justusschock — APPROVED** [review]

**Comment by woqidaideshi** [comment]
@awaelchli @Borda @lexierule @justusschock @akihironitta @carmocca 

Sorry. I am one of the maintainers of Bagua. Is it possible to keep Bagua in Lightning? We acutally released a new version (v0.9.1) in October 2022 without including it on the release page. Now we have added this new version to the release page (<https://github.com/BaguaSys/bagua/releases>). We are also maintaining this project, e.g., developing new features such as sparsification and compression, as well as bug fix, etc. We plan to release a new version this year, too. It would be great to keep it in the Lightning and glad to share more information about it if required.

**Comment by awaelchli** [comment]
@woqidaideshi Thanks for the infos. We will get back to you shortly with a proposal :)

**Comment by Borda** [comment]
@woqidaideshi we are moving most of strategies to separate/independent packages so to still be very easy to use but also allow them to evolve on their own phase... See example with #16757

**Comment by BinhangYuan** [comment]
Hi @awaelchli @Borda, I think this would be a solid solution if it makes the maintenance of the whole project easier. Is there some concrete instruction about how to enable such independent packages? How shall we contribute towards this? Thanks!

**Comment by woqidaideshi** [comment]
@awaelchli @Borda Thanks! Looking forward to the proposal and the concrete steps.

**Pull request merged**
