### PR TITLE
app: try to run tests in parallel

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

recently the test started to take much longer, but not sure it this will affect some port usage :rabbit: 

closes #17717 as it would need more debugging and the Apps are unstable...

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

cc @carmocca @borda

### CODE REVIEW

**Comment by Borda** [comment]
let's stay with parallel here and randomized in separate PR: #17460

**Comment by Borda** [comment]
Seems like these three test does not like parallel runs...
```
FAILED tests_app/components/python/test_python.py::test_tracer_component_with_code - assert 'An error' in '  File "/Users/runner/work/lightning/lightning/src/lightning_app/utilities/proxies.py", line 361, in __call__\n    return self.work_run(*args, **kwargs)\n\n  File "/Users/runner/work/lightning/lightning/src/lightning_app/components/python/tracer.py", line 169, in run\n    raise FileNotFoundError(f"The provided `script_path` {self.script_path}` wasn\'t found.")\n\nFileNotFoundError: The provided `script_path` file.py` wasn\'t found.\n'
 +  where '  File "/Users/runner/work/lightning/lightning/src/lightning_app/utilities/proxies.py", line 361, in __call__\n    return self.work_run(*args, **kwargs)\n\n  File "/Users/runner/work/lightning/lightning/src/lightning_app/components/python/tracer.py", line 169, in run\n    raise FileNotFoundError(f"The provided `script_path` {self.script_path}` wasn\'t found.")\n\nFileNotFoundError: The provided `script_path` file.py` wasn\'t found.\n' = WorkStatus(stage='failed', timestamp=1682376964.147671, reason='user_exception', message='  File "/Users/runner/work/lightning/lightning/src/lightning_app/utilities/proxies.py", line 361, in __call__\n    return self.work_run(*args, **kwargs)\n\n  File "/Users/runner/work/lightning/lightning/src/lightning_app/components/python/tracer.py", line 169, in run\n    raise FileNotFoundError(f"The provided `script_path` {self.script_path}` wasn\'t found.")\n\nFileNotFoundError: The provided `script_path` file.py` wasn\'t found.\n', count=1).message
 +    where WorkStatus(stage='failed', timestamp=1682376964.147671, reason='user_exception', message='  File "/Users/runner/work/lightning/lightning/src/lightning_app/utilities/proxies.py", line 361, in __call__\n    return self.work_run(*args, **kwargs)\n\n  File "/Users/runner/work/lightning/lightning/src/lightning_app/components/python/tracer.py", line 169, in run\n    raise FileNotFoundError(f"The provided `script_path` {self.script_path}` wasn\'t found.")\n\nFileNotFoundError: The provided `script_path` file.py` wasn\'t found.\n', count=1) = <lightning_app.components.python.tracer.TracerPythonScript object at 0x137900670>.status
FAILED tests_app/cli/test_run_app.py::test_lightning_run_app[True] - AssertionError: expected call not found.
Expected: launch('http://127.0.0.1:49547/view')
Actual: launch('http://127.0.0.1:7501/view')
FAILED tests_app/structures/test_structures.py::test_structures_with_payload - Failed: Timeout >300.0s
```

**Comment by Borda** [comment]
compare to master right now, it cuts effectively 5min from each run...
https://github.com/Lightning-AI/lightning/actions/runs/4794773536

**Review by lantiga — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
Nice !

**Review by justusschock — APPROVED** [review]

**Pull request merged**
