### PR TITLE
[LAI] Rename instances of "lightning_app" and "pytorch_lightning"

### PR DESCRIPTION
**Pull request by otaj**
Part of #15122 

When we will be creating full package and replace all occurrences of strings `lightning_lite`, `lightning_app` and `pytorch_lightning`, we need to make sure we don't replace these occurrences within variable/function names as these would produce syntax errors

cc @justusschock @awaelchli @rohitgr7 @borda

### CODE REVIEW

**Review by Borda — CHANGES_REQUESTED** [review]
This imply significant APPI change, anyway why this is needed when this is already solved in https://github.com/Lightning-AI/lightning/pull/15105/files#r1000350794

**Review by Borda — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
LGTM !

**Review by manskx — APPROVED** [review]

**Comment by manskx** [comment]
How we will deal with imports that contain either "lightning_app" or "pytorch_lightning" ?

**Comment by Borda** [comment]
> How we will deal with imports that contain either "lightning_app" or "pytorch_lightning" ?

what do you mean? the imports for `lightning.XXX` shall be corrected in the following PR #15105

**Pull request merged**
