### PR TITLE
docs: updating logos

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

cc @borda @carmocca @justusschock @awaelchli

### CODE REVIEW

**Review by lantiga — APPROVED** [review]

**Comment by awaelchli** [comment]
The texts are much smaller than before, and the subtitle "Created by Ligihtning AI" appears tiny. Is this intentional?

**Comment by lantiga** [comment]
BTW it seems the new images have a different logos

image

**Comment by Borda** [comment]
> The texts are much smaller than before, and the subtitle "Created by Lightning AI" appears tiny on the generated website. Is this intentional?

@alexlouiserose @likethecognac ^^

**Comment by Borda** [comment]
this is how the docs will look like: https://pytorch-lightning--18375.org.readthedocs.build/en/18375/

**Comment by likethecognac** [comment]
yes, had called out the small copy size myself ,when we first added the byline, but it was intentionally on the smaller side. fwiw it's called micro in our design system and to be used sparingly. are you inserting that updated image into the same sized div? The added byline may be making it not fit into the original space as easily. here's a mock to share what is expected
image
@lantiga yes, the original icon (logo) and wordmark (brand text) was actually one typeface and a different custom wordmark for "lighting", so those two aren't even the same font. Keeping the sub brands in a more easily changeable format for now to more easily update for things like lit-LLaMA > Llama , or addign spaces or changing lit-parrot > GPT, etc.

**Review by awaelchli — APPROVED** [review]

**Comment by awaelchli** [comment]
We would need to slightly adjust the size to fit what is expected as pointed out by @likethecognac. If this is not controllable here in lightning, it might need adjustment in the docs template.

**Comment by Borda** [comment]
I believe we need to update this CSS to set some higher max size but preserve max-width:
https://github.com/Lightning-Universe/lightning_sphinx_theme/blob/2c040181e16bcfcf98a1c3d7fcc92ecfa984c7e1/scss/shared/_navigation.scss#L34
cc: @adamjkuhn

**Review by carmocca — APPROVED** [review]
Low confidence on the logo changes. Approving to unblock

**Pull request merged**
