### PR TITLE
Enable Intel xpu as a new backend of PyTorch-Lightning

### PR DESCRIPTION
**Pull request by jingxu10**
Enable Intel xpu as a new backend of PyTorch-Lightning.
Contributed by [abhilash.majumder@intel.com](mailto:abhilash.majumder@intel.com) and [jing.xu@intel.com](mailto:jing.xu@intel.com).

Fixes #\<issue_number>

<details>
  <summary><b>Before submitting</b></summary>

- Was this **discussed/agreed** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- Did you make sure to **update the documentation** with your changes? (if necessary)
- Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- Did you list all the **breaking changes** introduced by this pull request?
- Did you **update the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

</details>

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

<details>
  <summary>Reviewer checklist</summary>

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

</details>

### CODE REVIEW

**Comment by jingxu10** [comment]
Any suggestions how can I stop pre-ci editing my code, but still correcting format?
image

**Comment by lantiga** [comment]
Hi @jingxu10 thank you for the contribution, lots of work went into that.

We are currently looking into making adding devices something you can do externally, so we keep Lightning core lean. This PR looks like a very good case we can look at to enable that kind of mechanism. This will likely happen after 2.0 lands.

So we can't merge the PR as is, but you're encouraged to reach out in our Slack at pytorch-lightning.slack.com so we can coordinate on how we can make it happen.

**Comment by abhilash1910** [comment]
@lantiga  Thanks for the info; when is the tentative plan for 2.0 release . I do see some refactorings which are in progress.

**Review by abhilash1910 — CHANGES_REQUESTED** [review]
@abhilash1910 to check deepspeed /ddp for WLs.

Any xpu.empty_caches should be placed in try blocks to ensure satefy.

**Comment by Borda** [comment]
Will be ported to separate repo, stay tuned! 🐿️

**Comment by Borda** [comment]
will be implemented as standalone extension

**Pull request closed without merging**
